### ISSUE TITLE
Análisis y diseño del Módulo 1

### ISSUE THREAD

**Issue by Andrea0312** [Andrea0312/ISOFT2-2021-C04#1]
Hola @JoseAlbertoSeco, he intentado terminar el diseño del módulo 1 pero me han surgido varias dudas:
        1. Al realizar el diagrama de comunicación no le veo sentido al caso de uso "Cerrar pedido". En mi opinión lo incluiría junto 
         con el caso de uso de "Imprimir cuenta" que se encuentra en el módulo 5.
        2. Y también el caso de uso de "Seleccionar numero de mesa " se realiza una vez que los clientes piden la comanda, por lo 
       tanto, creo que no deberíamos incluirlo aquí.
Espero que me des tu opinión respecto a ello, para ver si ponemos llegar a una conclusión en conjunto.
Te dejo el link [aquí](https://pruebasaluuclm-my.sharepoint.com/personal/josealberto_seco_alu_uclm_es/_layouts/15/onedrive.aspx?FolderCTID=0x012000B2A3AD929DDDDD49A103BFDABC50D1EF&id=%2Fpersonal%2Fjosealberto%5Fseco%5Falu%5Fuclm%5Fes%2FDocuments%2FCurso%203%2F1er%20Cuatrimestre%2FIngenieria%20del%20Software%20II%2FLaboratorio%2FTrabajo%2FISO2CasosDeUsoM1%2Evpp&parent=%2Fpersonal%2Fjosealberto%5Fseco%5Falu%5Fuclm%5Fes%2FDocuments%2FCurso%203%2F1er%20Cuatrimestre%2FIngenieria%20del%20Software%20II%2FLaboratorio%2FTrabajo)

**Comment by JoseAlbertoSeco** [comment]
Muy buenas @Andrea0312, vamos por partes:

  1. El RF "Cerrar pedido de mesa" se incluyó en el CdU _Gestionar mesa_ porque afecta a la tabla _mesa_ de la BD, ya que concluyes el servicio y almacenas los tiempos para computar las estadísticas. No se relaciona con la comanda ese RF.

1. 

1. 


1. 

sin embargo, el de "Imprimir cuenta" sí que afecta a las Comandas. Motivo por el que está en e

**Comment by JoseAlbertoSeco** [comment]
Muy buenas @Andrea0312, vamos por partes:

**1.** El RF "Cerrar pedido de mesa" se incluyó en el CdU _Gestionar mesa_ porque afecta a la tabla _mesa_ de la BD, ya que concluyes el servicio y almacenas los tiempos para computar las estadísticas. No se relaciona con la comanda ese RF. Sin embargo, el de "Imprimir cuenta" sí que afecta a las Comandas. Motivo por el que está en el CdU _Gestionar Comanda_.

**2.** No tiene mucho sentido lo que planteas. El camarero primero selecciona el número de la mesa y luego toma nota a los clientes. No puede (o mejor dicho, debe) anotar la comanda antes que seleccionar el número de mesa. Complicaría luego el vincular la comanda a la mesa, mientras que de la otra manera sabes que esa comanda _x_ va a ser de la mesa _n_.

Aún así, luego lo podemos ver tranquilamente y decidimos entre todos.
