### ISSUE TITLE
Base de Datos

### ISSUE THREAD

**Issue by JoseAlbertoSeco** [Andrea0312/ISOFT2-2021-C04#2]
Buenas a **todos**,

Recordad que tengo la BD en mi ordenador, por tanto, siempre que vayáis ha hacer alguna prueba o algo comunicarmelo para levantar la BD.
Tampoco olvidéis que en la otra reunión no conseguimos hacer una sentencia _SELECT_ desde Eclipse. Tenemos que tener esas cosas controladas para la próxima semana, más que nada porque @PabloVelascoCrespo y @SilvestreSanchez empiezan a implementar el CdU1 (Gestionar Mesa).

**Comment by PabloVelascoCrespo** [comment]
Buenas,
Hemos estado implementando el CdU1 e intentando solucionar lo del SELECT. Creemos que tenemos lo del SELECT ya bien hecho, por lo que quería pedirte si mañana por la mañana puedes abrir la base de datos para comprobarlo.

**Comment by PabloVelascoCrespo** [comment]
![SELECT](https://user-images.githubusercontent.com/72821847/99256858-511a4600-2816-11eb-806d-b8bd8cf728b0.png)
Chicos ya lo tenemos!
