### ISSUE TITLE
Análisis y diseño módulo 3

### ISSUE THREAD

**Issue by ghost** [Andrea0312/ISOFT2-2021-C04#3]
Buenas tardes @MiguelPellicerDominguez me ha surgido una duda a la hora de realizar el diagrama de comunicación, tenemos que realizar alguna suposición acerca de quién es el encargado de realizar el pedido de bebidas al camarero de mesa, ya que no se describe claramente en el enunciado.

**Comment by MiguelPellicerDominguez** [comment]
Buenas tardes @LuisPati , es cierto que en el enunciado no se especifica claramente quién realiza esa acción, por lo tanto, pensando de que trata de un restaurante el cargo reservado para realizar dicha acción es el camarero que recoge la comanda en la mesa atendida.

**Comment by ghost** [comment]
De acuerdo, creo que estás en lo cierto. Gracias!!!
