### ISSUE TITLE
Módulo 1

### ISSUE THREAD

**Issue by JoseAlbertoSeco** [Andrea0312/ISOFT2-2021-C04#4]
@PabloVelascoCrespo y @SilvestreSanchez ¿cómo váis con la implementación del módulo 1?

**Comment by PabloVelascoCrespo** [comment]
Ya está prácticamente, tengo que cambiar una cosa. Para esta tarde debería estar.

**Comment by SilvestreSanchez** [comment]
Ya está todo acabado, ya hemos hecho el commit.
