### ISSUE TITLE
Testing iteración 1

### ISSUE THREAD

**Issue by ghost** [Andrea0312/ISOFT2-2021-C04#5]
Muy buenas chicos, estamos trabajando @MiguelPellicerDominguez y yo en la elaboración del testing del módulo 1, y nos han surgido algunos problemas al respecto. Por lo tanto, hemos contactado con Andrés para reunirnos esta tarde con él y tenerlo finalizado lo antes posible.

**Comment by Andrea0312** [comment]
Buenos días chicos, pues ya nos comentáis que tal ha ido y si os ha resuelto las dudas.
