### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by ghost** [Andrea0312/ISOFT2-2021-C04#7]
Mi compañero @MiguelPellicerDominguez y yo no podemos empezar aún con la implementación de la iteración 4, debido a que necesitamos el diseño de la misma.

**Comment by PabloVelascoCrespo** [comment]
Estamos con ello, en cuanto esté os lo comunicaremos.

**Comment by PabloVelascoCrespo** [comment]
Ya lo tenéis, disculpad el retraso.
